### ISSUE TITLE
not chinese

### ISSUE THREAD

**Issue by makuchyharry** [cdians/youyiPUBG#7]
How to buy or use if not chinese

**Comment by cdians** [comment]
Multi-language versions are already on the drawing board

**Comment by cdians** [comment]
> How to buy or use if not chinese
Multi-language versions are already on the drawing board

**Comment by makuchyharry** [comment]
but you need to have QQ account ?

**Comment by cdians** [comment]
> but you need to have QQ account ?

it may be possible to use the license file to activate

**Comment by makuchyharry** [comment]
and how to buy license

**Comment by cdians** [comment]
> and how to buy license

free
